/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processor_MatrixProcessor */

#ifndef _Included_processor_MatrixProcessor
#define _Included_processor_MatrixProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     processor_MatrixProcessor
 * Method:    resetGPU
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_resetGPU
  (JNIEnv *, jclass, jint);

/*
 * Class:     processor_MatrixProcessor
 * Method:    isGPUEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_processor_MatrixProcessor_isGPUEnabled
  (JNIEnv *, jclass);

/*
 * Class:     processor_MatrixProcessor
 * Method:    getDeviceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_processor_MatrixProcessor_getDeviceCount
  (JNIEnv *, jclass);

/*
 * Class:     processor_MatrixProcessor
 * Method:    createSparseMatrix
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_processor_MatrixProcessor_createSparseMatrix
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     processor_MatrixProcessor
 * Method:    createDenseMatrix
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_processor_MatrixProcessor_createDenseMatrix
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     processor_MatrixProcessor
 * Method:    deleteSparseMatrix
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_processor_MatrixProcessor_deleteSparseMatrix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    deleteDenseMatrix
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_processor_MatrixProcessor_deleteDenseMatrix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    getSparseData
 * Signature: (J)[Lprocessor/Cell;
 */
JNIEXPORT jobjectArray JNICALL Java_processor_MatrixProcessor_getSparseData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    getDenseData
 * Signature: (J[I[I)[Lprocessor/Cell;
 */
JNIEXPORT jobjectArray JNICALL Java_processor_MatrixProcessor_getDenseData
  (JNIEnv *, jclass, jlong, jintArray, jintArray);

/*
 * Class:     processor_MatrixProcessor
 * Method:    setSparseData
 * Signature: (J[I[I[F)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_setSparseData
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jfloatArray);

/*
 * Class:     processor_MatrixProcessor
 * Method:    setDenseData
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_setDenseData
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     processor_MatrixProcessor
 * Method:    subtract
 * Signature: (JJIJ)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_subtract
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    sum
 * Signature: (JJIJ)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_sum
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    multiply
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_multiply
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    confidence
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_confidence
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    getMin
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_processor_MatrixProcessor_getMin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    getMax
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_processor_MatrixProcessor_getMax
  (JNIEnv *, jclass, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    binarize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_binarize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    transpose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_transpose
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    invert
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_invert
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    diagonalize
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_diagonalize
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    upperDiagonal
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_upperDiagonal
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    lowerDiagonal
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_lowerDiagonal
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     processor_MatrixProcessor
 * Method:    transitiveClosure
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_processor_MatrixProcessor_transitiveClosure
  (JNIEnv *, jclass, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
